onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /cpustim/cpu/clk
add wave -noupdate /cpustim/cpu/reset
add wave -noupdate /cpustim/cpu/instr
add wave -noupdate /cpustim/cpu/opcode11
add wave -noupdate /cpustim/cpu/opcode10
add wave -noupdate /cpustim/cpu/opcode8
add wave -noupdate /cpustim/cpu/opcode6
add wave -noupdate /cpustim/cpu/Reg2Loc
add wave -noupdate /cpustim/cpu/AluSrc
add wave -noupdate /cpustim/cpu/MemToReg
add wave -noupdate /cpustim/cpu/RegWrite
add wave -noupdate /cpustim/cpu/MemWrite
add wave -noupdate /cpustim/cpu/BranchTaken
add wave -noupdate /cpustim/cpu/UncondBr
add wave -noupdate /cpustim/cpu/LSRShift
add wave -noupdate /cpustim/cpu/ALuOp
add wave -noupdate /cpustim/cpu/RD
add wave -noupdate /cpustim/cpu/RM
add wave -noupdate /cpustim/cpu/RN
add wave -noupdate /cpustim/cpu/Ab
add wave -noupdate /cpustim/cpu/imm9
add wave -noupdate /cpustim/cpu/imm12
add wave -noupdate /cpustim/cpu/imm19
add wave -noupdate /cpustim/cpu/imm26
add wave -noupdate /cpustim/cpu/DW
add wave -noupdate /cpustim/cpu/A
add wave -noupdate /cpustim/cpu/B
add wave -noupdate /cpustim/cpu/BRegOut
add wave -noupdate /cpustim/cpu/DAddr9
add wave -noupdate /cpustim/cpu/Imm12
add wave -noupdate /cpustim/cpu/CondADr19
add wave -noupdate /cpustim/cpu/BrAddr26
add wave -noupdate /cpustim/cpu/NextInstr
add wave -noupdate /cpustim/cpu/UncondAdderOut
add wave -noupdate /cpustim/cpu/Adder4BitOUt
add wave -noupdate /cpustim/cpu/OutputPC
add wave -noupdate /cpustim/cpu/UncodMuxOut
add wave -noupdate /cpustim/cpu/shift2Out
add wave -noupdate /cpustim/cpu/clK
add wave -noupdate /cpustim/cpu/result
add wave -noupdate /cpustim/cpu/ImmCntr
add wave -noupdate /cpustim/cpu/SetFlag
add wave -noupdate /cpustim/cpu/zero
add wave -noupdate /cpustim/cpu/overflow
add wave -noupdate /cpustim/cpu/negative
add wave -noupdate /cpustim/cpu/AluCout
add wave -noupdate /cpustim/cpu/ZeroFlag
add wave -noupdate /cpustim/cpu/NegFlag
add wave -noupdate /cpustim/cpu/OverFlag
add wave -noupdate /cpustim/cpu/memOut
add wave -noupdate /cpustim/cpu/MemToRegOUt
add wave -noupdate /cpustim/cpu/shamt
add wave -noupdate /cpustim/cpu/shift3Out
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {10000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 100
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {360024 ps}
